### ISSUE TITLE
"bad command" error when pulling a gitolite repository

### ISSUE THREAD

**Issue by tommie-lie** [jelmer/dulwich#384]
I recently noticed (after a Debian sid dist-upgrade) that dulwich won't play nicely with $workplace's gitolite repository anymore.

```
$ hg pull
pulling from git+ssh://git@git.workplace.tld:repo.git/
bad command: git-upload-pack repo.git
abort: git remote error: The remote server unexpectedly closed the connection.
```

In gitolite's log, I see the following message (sic!):
```
git-upload-pack bw-fla.git
Die generated at line 1180 in /home/git/bin/gitolite.pm : bad command: git-upload-pack repo.git<<newline>> <<newline>>
```
Downgrading to an older version of dulwich (Debian version 0.10.1+git20150425-1 is the last working version) solves the problem and the gitolite log then says:
```
git-upload-pack 'repo.git'
```

Clearly, the git-upload-pack command line is constructed in a wrong way for gitolite to understand it correctly. The obvious difference in the printed command strings are the missing single quote characters arout the repository name.

**Comment by jelmer** [comment]
This should be fixed in master, can you try that?

Jelmer

**Comment by tommie-lie** [comment]
Sorry, latest dulwich master (6ae640 ) does not fix the issue for me.
gitolite uses a regular expression to verify that the requested command is a valid git command. Both, our ancient version of gitolite and the recent git master I checked use a regex that force single quotes around the repo name. After merging #294, the quotes are gone and gitolite's log messages indicate that this is indeed the problem.

For me, just adding the single quotes around the path variable in [dulwich/client.py:912](https://github.com/jelmer/dulwich/blob/6ae640a463ac75015545cb6c1d7d7df267aa2508/dulwich/client.py#L912) fixes the issue. I hope this won't break on Windows machines (I'm not familiar with cmd.exe's string quoting).

Do you want a pull request for that?


P.S.: Sorry, forgot to mention that I use mercurial-git as a "frontend" to dulwich, though that might be clear from my example command line.

**Comment by jelmer** [comment]
Yeah, please do send a pull request.

**Comment by jelmer** [comment]
Ah, it looks like C git behaves differently than I was expecting. It's taking a single string argument with the entire shell command to run rather than an argv (list of strings).

**Comment by jelmer** [comment]
From running strace locally:

foo.18926:execve("/usr/bin/ssh", ["ssh", "github.com", "git-upload-pack '/git/git'"], [/* 46 vars */]) = 0

**Comment by jelmer** [comment]
Merged, with some additional modifications. Thanks!
